# Generated by Django 6.0.2 on 2026-04-16 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_rls_policies'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='client_email',
            field=models.EmailField(blank=True, max_length=200, null=True, verbose_name='Email Cliente'),
        ),
        migrations.AddField(
            model_name='organization',
            name='client_first_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre Cliente'),
        ),
        migrations.AddField(
            model_name='organization',
            name='client_last_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Apellido Cliente'),
        ),
        migrations.AddField(
            model_name='organization',
            name='client_phone',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Teléfono Cliente'),
        ),
        migrations.AddField(
            model_name='organization',
            name='country',
            field=models.CharField(default='Panamá', max_length=100, verbose_name='País'),
        ),
    ]
