# Generated by Django 6.0.2 on 2026-04-19 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_activity_organization_and_more'),
        ('organizations', '0004_patch_rls_policy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficiary',
            name='ci',
            field=models.CharField(blank=True, help_text='Cédula de identidad o número de gafete QR', max_length=50, null=True, verbose_name='Cédula o ID Local'),
        ),
        migrations.AddConstraint(
            model_name='beneficiary',
            constraint=models.UniqueConstraint(condition=models.Q(('ci__isnull', False)), fields=('organization', 'ci'), name='unique_ci_per_org'),
        ),
    ]
